### ISSUE TITLE
Struktura danych w tabeli

### ISSUE THREAD

**Issue by AsteRons** [AsteRons/IoT_project#13]
Potrzebuje informacji jakie dane będą zapisane w tabeli i jak będziemy je wyświetlać?

**Comment by wojtaskamil** [comment]
Jeśli chodzi o odczyt z czujnika (SEN0189) to jest to wartość od 0 - 4,5V, która przekłada się na mętność wody w zależności jak na tym diagramie:
https://raw.githubusercontent.com/DFRobot/DFRobotMediaWikiImage/master/Image/_relationship_diagram.jpg
W skrócie - odczyt z czujnika to będzie jedna dana. Napięcie przeliczę na Arduino według tego diagramu i podam w jednostce NTU (Nephelometric Turbidity Unit)

**Comment by MarcinJ7** [comment]
@wojtaskamil  spoko, a więc wstępna struktura bazy danych będzie następująca

![obraz](https://user-images.githubusercontent.com/49407119/66420690-9f032e80-ea06-11e9-9082-c188a97f9c49.png)

Bazę ogarnę na dniach i w czwartek po południu podam wszystkie parametry DB do @AsteRons .

**Comment by AsteRons** [comment]
Format datatime: yyyy-MM-dd HH:mm:ss
Format ID: int
Może dodamy jeszcze 4 wartość oznaczającą unikalny numer urządzenia? Dzięki temu będziemy mogli wpiąć bez modyfikacji kodu nieskończoną liczbę czujników?

**Comment by MarcinJ7** [comment]
Spoko, to będzie deviceID jako int. Jutro zrobię bazę i zabieram się za pisanie skryptów o których dziś rozmawialiśmy

**Comment by MarcinJ7** [comment]
To teraz będzie taka struktura:
![obraz](https://user-images.githubusercontent.com/49407119/66555611-40959780-eb4f-11e9-8f13-1096ac6f604a.png)
