### ISSUE TITLE
Wgranie skryptów na serwer

### ISSUE THREAD

**Issue by MarcinJ7** [AsteRons/IoT_project#19]
Po napisaniu skryptów należy wgrać je na serwer w celu późniejszego przetestowania.

**Comment by MarcinJ7** [comment]
Podsumowanie mojej części DB + interfejs do niej:
Do @wojtaskamil :
Dane dodajemy poprzez uruchomienie skryptu "addToDB.php" znajdującego się na serwerze. Moduł wchodzi pod następujący adres: _https://iotprojectteam.000webhostapp.com/addToDB.php?deviceID=@&ntuValue=@_  Zamiast "@" oczywiście parametry pochodzące z czujników - tyle.
Do @AsteRons i @Mateusz:
Dane pobierać możecie w formacie JSON z bazy. Co do obróbki to na pewno wiecie co i jak - z @AsteRons już pisałem (ogarnie na luzie JSONy). Żądanie pobrania danych przez uruchomienie skryptu "dataDBtoJSON.php" znajdującego się na serwerze pod adresem: _https://iotprojectteam.000webhostapp.com/dataDBtoJSON.php_ Skrypt dla podglądu wypisuje w przeglądarce dane, ale są też dostępne do przechwycenia.
Do wszystkich: 
Są jeszcze 2 skrypty: "showDBcontent.php" oraz  "deleteDBcontent.php". 
Pierwszy wypisuje wszystkie dane z tabeli DB w oknie przeglądarki, a drugi: kasuje **wszystkie** dane z bazy, więc uważajcie :+1: 
"showDBcontent.php" - adres: _https://iotprojectteam.000webhostapp.com/showDBcontent.php_
"deleteDBcontent.php" - _adres: https://iotprojectteam.000webhostapp.com/deleteDBcontent.php_

To już wszystko, przechodzę na projektową emeryturę :relaxed: jakbyście chcieli ogarnąć inny serwer to po prostu skorzystajcie z tych linków i baza danych będzie ogarnięta. Powodzenia w hardware i froncie, 
Zamykam Issue kropka.

**Comment by mateusz** [comment]
Nieee ja z tym nie mam nic wspolnego XD
