### ISSUE TITLE
Stworzenie bazy danych i użytkowników

### ISSUE THREAD

**Issue by AsteRons** [AsteRons/IoT_project#2]
Baza danych: MySQL ??

Potrzebuje:
- nazwę hosta (lub IP)
- port 
- nazwa bazy
oraz 
- nazwa użytkownika
- hasło użytkownika

**Comment by MarcinJ7** [comment]
Dodałem do bazy danych jakieś przykładowe dane. Nie patrzcie na timestamp bo na początku nie była ustawiony sqlem nasza strefa czasowa tylko ta, gdzie "fizycznie" znajduje się baza - teraz już ustawione (kolumna nie ma w sumie żadnego znaczenia w obecnej chwili). Zrzut ekranu z zawartością bazy:

![obraz](https://user-images.githubusercontent.com/49407119/66565227-42b52180-eb62-11e9-9799-e52dbaf84cb3.png)

Teraz będę pisał skrypty pozwalające na dodawanie danych do bazy, odczyt, kasowanie wszystkich danych itp itd.
