### ISSUE TITLE
Poprawienie wyglądu strony głównej

### ISSUE THREAD

**Issue by AsteRons** [AsteRons/IoT_project#27]

**Comment by AsteRons** [comment]
Poprawienie wyglądu strony głównej, która znajduje się w : IoT_project\Software\iotserver\src\main\resources\templates\sensorData
- graph-sensorData - html z wykresem
- list-sensorData - html ze stroną główną

Można dodać tutaj nowy Html z opisem, innym wykresem albo coś takiego.
Po stworzeniu nowych plików html i dodaniu przycinków do strony głównej można @AsteRons doda je na server

**Comment by KruczekM** [comment]
Ostateczne poprawki zostały naniesione.
