### ISSUE TITLE
Dodanie strony z opisem projektu

### ISSUE THREAD

**Issue by AsteRons** [AsteRons/IoT_project#28]

**Comment by AsteRons** [comment]
Dodanie dodatkowego pliku Html z opisem.
Coś jak na innych stronach jest zakładka "O nas".
 Krótka dokumentacja, zdjęcia itp. Niech każdy coś przygotuje ze swojej części, potem @KruczekM  zrobi stronę a @AsteRons doda ją do naszego servera.

**Comment by KruczekM** [comment]
Sprawozdanie z projektu zostanie umieszczone na Isodzie.
