### ISSUE TITLE
Integracja czujnik -> baza danych

### ISSUE THREAD

**Issue by AsteRons** [AsteRons/IoT_project#29]
Stworzenie połączenia między czujnikiem a bazą danych

**Comment by AsteRons** [comment]
Tutaj wpisujemy problemy w jakie wystąpią w trakcie integracji czujnik -> baza danych

**Comment by MarcinJ7** [comment]
Po dodaniu tokena @wojtaskamil musi zapisać go w pamięci mikrokontrolera. Następnie będzie należało przetestować działanie skryptów wykorzystujących ten token (dodawanie, usuwanie, odczyt).

**Comment by MarcinJ7** [comment]
Integracja zakończona - wszystko działa prawidłowo.
